modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Focamacho/MysticalAdaptations/issues"
[[mods]]
modId="mysticaladaptations"
version="${file.jarVersion}"
displayName="Mystical Adaptations"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations"
credits="BlakeBr0 for Mystical Agriculture"
authors="Focamacho"
description='''
Seed Extractors, Insanium Armor, Insanium Tools and more.
'''
[[dependencies.mysticaladaptations]]
    modId="mysticalagriculture"
    mandatory=true
    versionRange="[3,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.mysticaladaptations]]
    modId="mysticalagradditions"
    mandatory=true
    versionRange="[3,]"
    ordering="BEFORE"
    side="BOTH"