modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Focamacho/MysticalAdaptations/issues"
license="MIT-1.0"
[[mods]]
modId="mysticaladaptations"
version="1.16.5-1.2.0"
displayName="Mystical Adaptations"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations"
credits="BlakeBr0 for Mystical Agriculture"
authors="Focamacho"
description='''Seed Extractors, Insanium Armor, Insanium Tools and more.'''
[[dependencies.mysticaladaptations]]
    modId="mysticalagriculture"
    mandatory=true
    versionRange="[4,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.mysticaladaptations]]
    modId="mysticalagradditions"
    mandatory=true
    versionRange="[4,]"
    ordering="BEFORE"
    side="BOTH"