modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Focamacho/MysticalAdaptations/issues"
license="MIT-1.0"
[[mods]]
modId="mysticaladaptations"
version="1.18.2-1.1.1"
displayName="Mystical Adaptations"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations"
credits="BlakeBr0 for Mystical Agriculture"
authors="Focamacho"
description='''Insanium Armor, Insanium Tools and more.'''
[[dependencies.mysticaladaptations]]
    modId="mysticalagriculture"
    mandatory=true
    versionRange="[4,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.mysticaladaptations]]
    modId="mysticalagradditions"
    mandatory=true
    versionRange="[4,]"
    ordering="BEFORE"
    side="BOTH"